kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-agent-data
  namespace: devops
spec:
  storageClassName: jenkins-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
